[project]
name = "translated-captions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "argostranslate>=1.9.6",
    "faster-whisper>=1.1.1",
    "langdetect>=1.0.9",
    "numpy>=2.2.6",
    "sounddevice>=0.5.2",
]
